baseURL = "https://navcore.org"
theme = "nav-community-v1"

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir = true

[languages]
[languages.en]
title = "NavCoin Community Site"
weight = 1
languageName = "English"

[languages.ru]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Russian"


twitter_username = "navcoin"


#linkedin = "english-link"
#
#languageCode = "en"
#DefaultContentLanguage = "en"
#copyright = "Everything is mine"
#
#
#[languages]
#[languages.en]
#title = "NavCoin Community Site"


[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[taxonomies]
  category = "categories"
  filter = "filter"
# Main Menu
[[languages.en.menu.main]]
    name = "Home"
    title = "Home"
    weight = -130
    identifier = "home"
    url = "/"
[[languages.en.menu.main]]
    name = "News"
    title = "News"
    weight = -120
    identifier = "news"
    url = "/news/"
[[languages.en.menu.main]]
    name = "Resources"
    title = "Resources"
    weight = -110
    identifier = "resources"
[[languages.en.menu.main]]
    parent = "resources"
    name = "Projects"
    title = "Projects"
    weight = -109
    identifier = "Project"
    url = "/projects/"
[[languages.en.menu.main]]
    parent = "resources"
    name = "Merchants"
    title = "Merchants"
    weight = -108
    identifier = "merchants"
    url = "/merchants/"
[[languages.en.menu.main]]
    parent = "resources"
    name = "Information"
    title = "Information"
    weight = -107
    identifier = "information"
    url = "/information/"
[[languages.en.menu.main]]
    name = "Roadmap"
    title = "Roadmap"
    weight = -105
    url = "/roadmap/"
    identifier = "roadmap"
[[languages.en.menu.main]]
    name = "Get Involved"
    title = "Get Involved"
    weight = -100
    url = "/get-involved/"
    identifier = "get-involved"

[[languages.en.menu.main]]
    name = "About"
    title = "About"
    weight = -90
    url = "/about-this-website/"
    identifier = "about-this-website"

[[languages.ru.menu.main]]
    name = "russia"
    title = "Home"
    weight = -130
    identifier = "home"
    url = "/"
[[languages.ru.menu.main]]
    name = "News"
    title = "News"
    weight = -120
    identifier = "news"
    url = "/news/"
[[languages.ru.menu.main]]
    name = "Resources"
    title = "Resources"
    weight = -110
    identifier = "resources"
[[languages.ru.menu.main]]
    parent = "resources"
    name = "Projects"
    title = "Projects"
    weight = -109
    identifier = "Project"
    url = "/projects/"
[[languages.ru.menu.main]]
    parent = "resources"
    name = "Merchants"
    title = "Merchants"
    weight = -108
    identifier = "merchants"
    url = "/merchants/"
[[languages.ru.menu.main]]
    parent = "resources"
    name = "Information"
    title = "Information"
    weight = -107
    identifier = "information"
    url = "/information/"
[[languages.ru.menu.main]]
    name = "Roadmap"
    title = "Roadmap"
    weight = -105
    url = "/roadmap/"
    identifier = "roadmap"
[[languages.ru.menu.main]]
    name = "Get Involved"
    title = "Get Involved"
    weight = -100
    url = "/get-involved/"
    identifier = "get-involved"

[[languages.ru.menu.main]]
    name = "About"
    title = "About"
    weight = -90
    url = "/about-this-website/"
    identifier = "about-this-website"
